image: { 
  repository: "", 
  tag: latest, 
  pullPolicy: IfNotPresent 
}
replicaCounts: { 
  web: 2,
  worker: 1
}

resources:
  web:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
  worker:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
  scheduler:
    requests: { cpu: 50m,  memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }
  redis:
    requests: { cpu: 50m,  memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }

# Most overridden by --set env.* at deploy time
env:
  DJANGO_SETTINGS_MODULE: statuspage.settings
  STATUS_PAGE_CONFIGURATION: statuspage.configuration
  STATUS_HOSTNAME: ""
  ALLOWED_HOSTS: ""
  SECRET_KEY: ""
  DATABASE_URL: ""
  REDIS_URL: "redis://statuspage-redis.statuspage.svc.cluster.local:6379/0"

  db:
    host: ""           
    port: 5432
    name: "statuspage" 
    user: "statuspage" 
    password: "" 

service: { 
  port: 8000
}

ingress:
  enabled: true
  className: alb
  alb: {
    scheme: internet-facing,
    target_type: ip,
    healthcheck_path: /
  }
  hosts:
    - host: status-page-ay.com
      paths:
        - path: /
          pathType: Prefix

acmArn: ""

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65

pdb:
  webMinAvailable: 1

migrations:
  enabled: true

collectstatic:
  enabled: true

manageNamespace: false
