image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/status-page-ay-repo
  tag: latest
  pullPolicy: Always

replicaCounts:
  web: 2
  worker: 1

resources:
  web:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
  worker:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
  scheduler:
    requests: { cpu: 50m,  memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }
  redis:
    requests: { cpu: 50m,  memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }

# Most overridden by --set env.* at deploy time
env:
  DJANGO_SETTINGS_MODULE: statuspage.settings
  STATUS_PAGE_CONFIGURATION: statuspage.configuration
  STATUS_HOSTNAME: ""
  ALLOWED_HOSTS: ""
  SECRET_KEY: ""
  DATABASE_URL: ""
  REDIS_URL: "redis://statuspage-redis.statuspage.svc.cluster.local:6379/0"

  db:
    host: ""           
    port: 5432
    name: "statuspage" 
    user: "statuspage" 
    password: "" 

service: { 
  port: 80, # what the Service (and ALB) will expose
  targetPort: 8000 # the port Gunicorn listens on inside the pod
}

ingress:
  enabled: true
  className: alb
  alb: {
    scheme: internet-facing,
    target_type: ip,
    healthcheck_path: /
  }
  hosts:
    - host: status-page-ay.com
      paths:
        - path: /
          pathType: Prefix

acmArn: ""

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65

pdb:
  webMinAvailable: 1

migrations:
  enabled: true

collectstatic:
  enabled: true

manageNamespace: false

s3:
  bucket: ""   # will fill in from Terraform output later
  region: us-east-1
  customDomain: ""
serviceAccount:
  create: true
  name: statuspage-web
  annotations: {}  # Terraform will inject IRSA annotation
