apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-nginx-conf
  namespace: statuspage
data:
  default.conf: |
    server {
      listen 80;

      location /static/ {
        alias /usr/share/nginx/html/static/;
        autoindex off;
      }

      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }