apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-web
  namespace: statuspage
spec:
  replicas: {{ .Values.replicaCounts.web }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: statuspage
      tier: web
  template:
    metadata:
      labels:
        app: statuspage
        tier: web
    spec:
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: statuspage-static
        - name: nginx-conf
          configMap:
            name: statuspage-nginx-conf
            items:
              - key: default.conf
                path: default.conf
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gunicorn","--workers","3","--bind","0.0.0.0:8000","--timeout","60","statuspage.wsgi"]
          ports:
            - name: gunicorn
              containerPort: 8000
          volumeMounts:
          - name: static-files
            mountPath: /app/statuspage/static
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ .Values.env.STATUS_HOSTNAME | default "status-page-ay.com" | quote }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ .Values.env.STATUS_HOSTNAME | default "status-page-ay.com" | quote }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          resources: {{- toYaml .Values.resources.web | nindent 12 }}

        - name: nginx
          image: nginx:1.25
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: static-files
              mountPath: /app/statuspage/static
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf


      