apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-worker
  namespace: statuspage
spec:
  replicas: {{ .Values.replicaCounts.worker }}
  selector:
    matchLabels:
      app: statuspage
      tier: worker
  template:
    metadata:
      labels:
        app: statuspage
        tier: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "/app/statuspage/manage.py", "rqworker", "high", "default", "low"]
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          env:
            - name: AWS_REGION
              value: {{ .Values.s3.region | quote }}
            - name: AWS_STORAGE_BUCKET_NAME
              value: {{ .Values.s3.bucket | quote }}
            #- name: AWS_S3_CUSTOM_DOMAIN
            #  value: {{ default "" .Values.s3.customDomain | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - rqworker
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources: {{- toYaml .Values.resources.worker | nindent 12 }}
