apiVersion: apps/v1
kind: Deployment
metadata: { 
  name: statuspage-worker, 
  namespace: statuspage
}
spec:
  replicas: {{ .Values.replicaCounts.worker }}
  selector: {
    matchLabels: {
      app: statuspage,
      tier: worker
    }
  }
  template:
    metadata: {
      labels: { 
        app: statuspage,
        tier: worker
      }
    }
    spec:
      containers:
        - name: worker
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python","statuspage/manage.py","rqworker","high","default","low"]
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          startupProbe:
            tcpSocket:
              port: 6379
              host: statuspage-redis
            #exec:
              #command: ["/bin/sh","-c","getent hosts redis || nslookup redis || ping -c1 redis"]
              #command: ["python","-c","import redis; r=redis.Redis(host='statuspage-redis', port=6379); r.ping()"]
            failureThreshold: 30
            periodSeconds: 5
          resources: {{- toYaml .Values.resources.worker | nindent 12 }}
