apiVersion: apps/v1
kind: Deployment
metadata: {
  name: statuspage-scheduler,
  namespace: statuspage
}
spec:
  replicas: 1
  selector: {
    matchLabels: {
      app: statuspage,
      tier: scheduler
    }
  }
  template:
    metadata: {
      labels: {
        app: statuspage,
        tier: scheduler
      }
    }
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python","/app/statuspage/manage.py","rqscheduler"]
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          env:
            - name: AWS_REGION
              value: {{ .Values.s3.region | quote }}
            - name: AWS_STORAGE_BUCKET_NAME
              value: {{ .Values.s3.bucket | quote }}
            #- name: AWS_S3_CUSTOM_DOMAIN
            #  value: {{ default "" .Values.s3.customDomain | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
          resources: {{- toYaml .Values.resources.scheduler | nindent 12 }}
