apiVersion: apps/v1
kind: Deployment
metadata: {
  name: statuspage-scheduler,
  namespace: statuspage
}
spec:
  replicas: 1
  selector: {
    matchLabels: {
      app: statuspage,
      tier: scheduler
    }
  }
  template:
    metadata: {
      labels: {
        app: statuspage,
        tier: scheduler
      }
    }
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python","/app/statuspage/manage.py","rqscheduler"]
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          resources: {{- toYaml .Values.resources.scheduler | nindent 12 }}
