{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: statuspage-migrate-{{ now | date "20060102150405" }}
  namespace: statuspage
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - sh
            - -c
            - |
              until nc -z statuspage-redis 6379; do
                echo "Waiting for redis..."
                sleep 2
              done
              python statuspage/manage.py migrate --noinput
          #command: ["python","statuspage/manage.py","migrate","--noinput"]
          envFrom:
            - secretRef:
                name: statuspage-secrets
            - configMapRef:
                name: statuspage-config
{{- end }}