{{- if .Values.collectstatic.enabled }}
apiVersion: batch/v1
kind: Job
metadata: 
  name: statuspage-collectstatic-{{ now | date "20060102150405" }}
  namespace: statuspage
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Never
      containers:
        - name: collectstatic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python","statuspage/manage.py","collectstatic","--noinput"]
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          env:
            - name: AWS_REGION
              value: {{ .Values.s3.region | quote }}
            - name: AWS_STORAGE_BUCKET_NAME
              value: {{ .Values.s3.bucket | quote }}
            # Optional if you’ll use a custom domain (CloudFront)
            #- name: AWS_S3_CUSTOM_DOMAIN
            #  value: {{ default "" .Values.s3.customDomain | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
{{- end }}
