{{- if .Values.collectstatic.enabled }}
apiVersion: batch/v1
kind: Job
metadata: 
  name: statuspage-collectstatic-{{ now | date "20060102150405" }}
  namespace: statuspage
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: collectstatic
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python","statuspage/manage.py","collectstatic","--noinput"]
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
{{- end }}
