{{- if .Values.collectstatic.enabled }}
apiVersion: batch/v1
kind: Job
metadata: 
  name: statuspage-collectstatic-{{ now | date "20060102150405" }}
  namespace: statuspage
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: collectstatic
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python","statuspage/manage.py","collectstatic","--noinput"]
          envFrom:
            - secretRef:
                name: statuspage-secrets
            - configMapRef:
                name: statuspage-config
{{- end }}
