{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: statuspage-migrate-{{ now | date "20060102150405" }}
  namespace: statuspage
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python","/app/statuspage/manage.py","migrate","--noinput"]      
          envFrom:
            - configMapRef: { name: statuspage-config }
            - secretRef: { name: statuspage-secrets }
          env:
            - name: AWS_REGION
              value: {{ .Values.s3.region | quote }}
            - name: AWS_STORAGE_BUCKET_NAME
              value: {{ .Values.s3.bucket | quote }}
            #- name: AWS_S3_CUSTOM_DOMAIN
            #  value: {{ default "" .Values.s3.customDomain | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
{{- end }}