apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statuspage-static
  namespace: statuspage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}