apiVersion: v1
kind: Secret
metadata:
  name: statuspage-secrets
  namespace: statuspage
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  DATABASE_URL: {{- if .Values.env.DATABASE_URL -}}{{ .Values.env.DATABASE_URL | quote }}{{- else -}}{{ printf "postgresql://%s:%s@%s:%v/%s?sslmode=require" .Values.env.db.user (urlquery .Values.env.db.password) .Values.env.db.host .Values.env.db.port .Values.env.db.name | quote }}{{- end }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}