apiVersion: v1
kind: Secret
metadata: { 
  name: statuspage-secrets, 
  namespace: statuspage 
}
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.env.SECRET_KEY }}"
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
  REDIS_URL: "{{ .Values.env.REDIS_URL }}"
