{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: statuspage
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
{{- end }}