apiVersion: v1
kind: Service
metadata:
  name: statuspage-web
  namespace: statuspage
spec:
  type: ClusterIP
  selector:
    app: statuspage
    tier: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
